%Initial Conditions
x0=[1, 0, 0.5, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0.2, 1, 1, 0.025,0, 0.1];

v_rated = 690; % Rated Voltage
s_rated = 2.75e6; % Rated power
wb = 2*pi*50; % Rated angular frequency
w_ref = 1; %Inverter frequency set point in p.u.
wg = 1; % Grid frequency in p.u.
Ta = 2; % VSM Inertia constant 
kd = 400; % VSM Damping co-efficient
kpc = 1.27; % Current Controller gain
kic = 14.3; % Current copntroller gain
kpv = 0.59; % Voltage controller gain
kiv = 736; % VOltage controller gain
p_ref = 0.5; % Active power reference in p.u.
kw = 20; % Frequency droop gain in p.u.
q_ref = 0; % Reactive power reference in p.u. 
kq = 0.2; % Reactive power droop gain in p.u.
wf = 1000; %Reactive power filter in rad/s
v_ref = 1.02; % Votlage referencfe in p.u. 
lf = 0.08; % Filter inductance in p.u.
rf = 0.003; % Filter resistance in p.u.
cf = 0.074; % Filter capacitance in p.u.
lg = 0.2; % Grid inductance in p.u.
rg = 0.01; % Grid resistance in p.u.
vg = 1.0; % Grid voltage in p.u. 
wad = 50; % Active damping filter
kad = 0.5; % Active damping gain 
lv = 0.2; % Virtual Inductance in p.u.
rv = 0; % Virtual resistance in p.u.
wlp = 500; % PLL filter in rad/s
kp_pll = 0.084; % PLL proportional gain
ki_pll = 4.69; % PLL integraql gain 
kffv = 0; % Binary variable enabling the votlage feed-forward in output of current controllers
kffi = 0;