function f = voltage_control(iod, vod, ioq, voq, icvd, icvq, gamma_d, gamma_q, params)

%get parameters

    kpv = params.kpv; % Voltage controller gain
    kiv = params.kiv; % Voltage controller gain
    wb = params.wb; 
    wg = params.wg; 
    lf = params.lf; % Filter inductance in p.u.
    rf = params.rf; % Filter resistance in p.u.
    cf = params.cf; % Filter capacitance in p.u.
    kad = params.kad; % Active damping gain 
    kffv = params.kffv; % Binary variable enabling the votlage feed-forward in output of current controllers
    kffi = params.kffi;
    kpc = params.kpc; % Current controller gain
    kic = params.kic; % Current controller gain

f = [
      %d(vo,d)/dt = 
      wb*wg*voq...
      +wb*icvd/cf...
      -wb*iod/cf;
      
      %d(vo,q)/dt=
      -wb*wg*vod...
      +wb*icvq/cf...
      -wb*ioq/cf;
      
      %d(icv,d)/dt = 
      (wb*(kffv-1-kad-kpc*kpv))*vod/lf...
      -wb*cf*kpc*wg*voq/lf...
      -wb*(kpc+rf)*icvd/lf...
      +wb*kic*gamma_d/lf+wb*kpc*(kffi-kpv*rv)*iod/lf...
      +wb*kpc*kpv*lv*wg*ioq/lf...
      +wb*kad*phi_d/lf...
      +wb*kiv*kpc*xi_d/lf...
      -wb*kpc*kpv*kq*qm/lf...
      -wb*icvq*delta_w_vsm...
      +wb*kpc*kpv*lv*ioq*delta_w_vsm/lf...
      -wb*cf*kpc*voq*delta_w_vsm/lf...
      +wb*kpc*kpv*kq*q_ref/lf+wb*kpc*kpv*v_ref/lf; 
      
      %d(icv,q)/dt = 
      wb*cf*kpc*wg*vod/lf...
      +(wb*(kffv-1-kad-kpc*kpv))*voq/lf...
      -wb*(kpc+rf)*icvq/lf...
      +wb*kic*gamma_q/lf...
      -wb*kpc*kpv*lv*wg*iod/lf...
      +wb*kpc*(kffi-kpv*rv)*ioq/lf...
      +wb*kad*phi_q/lf+wb*kiv*kpc*xi_q/lf...
      +wb*icvd*delta_w_vsm...
      -wb*kpc*kpv*lv*iod*delta_w_vsm/lf...
      -wb*cf*kpc*vod*delta_w_vsm/lf; 
  
      %d(xi_d)/dt = 
      -vod...
      -rv*iod...
      +lv*wg*ioq...
      -kq*qm...
      +lv*ioq*delta_w_vsm...
      +kq*q_ref...
      +v_ref;
      
      %d(xi_q)/dt = 
      -voq...
      -lv*wg*iod...
      -rv*ioq...
      -lv*iod*delta_w_vsm;
      
      ];

end

